on: 
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      GOOGLE_PROJECT: precise-truck-89123

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Get the version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/1060593636030/locations/global/workloadIdentityPools/github/providers/github
        service_account: gha-npm-packages@${{ env.GOOGLE_PROJECT }}.iam.gserviceaccount.com
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GOOGLE_PROJECT }}

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          build-${{ env.cache-name }}-
          build-
    - name: Install deps
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run lib

    - name: Set version in code
      run: npm version ${{ steps.version.outputs.VERSION }}

    - name: Login to registry
      run: npm run ar:login

    - name: Publish to NPM
      run: npm publish
